name: FukkuCoinPlugin
main: FukkuCoinPlugin
version: 1.0
api-version: 1.16
commands:
  createnpc:
    description: Tạo NPC shop
    usage: /createnpc <tên> <giá trị>
    permission: fukkucoin.createnpc
  movenpc:
    description: Di chuyển NPC đến vị trí người chơi
    usage: /movenpc <tên>
    permission: fukkucoin.movenpc
permissions:
  fukkucoin.createnpc:
    description: Cho phép tạo NPC shop
    default: op
  fukkucoin.movenpc:
    description: Cho phép di chuyển NPC
    default: op
