name: FukkuCoinPlugin
main: fukkucoin.FukkuCoinPlugin
version: 1.0
api-version: 1.21
commands:
  fukkucoin:
    description: Lệnh quản lý FukkuCoin
    usage: /<command> [args]
permissions:
  fukkucoin.admin:
    description: Quyền sử dụng lệnh quản trị FukkuCoin
    default: op
